'use client'



// import emojiSuggestion from './EmojiSuggestion/suggestion'
// import Document from '@tiptap/extension-document'
// import ListItem from '@tiptap/extension-list-item'
// import Heading from '@tiptap/extension-heading'
// import Image from '@tiptap/extension-image'
// import Link from '@tiptap/extension-link'
// import Table from '@tiptap/extension-table'
// import TableCell from '@tiptap/extension-table-cell'
// import TableHeader from '@tiptap/extension-table-header'
// import TableRow from '@tiptap/extension-table-row'



export { StarterKit } from '@tiptap/starter-kit'
export { Highlight } from '@tiptap/extension-highlight'
export { Underline } from '@tiptap/extension-underline'
export { Placeholder } from '@tiptap/extension-placeholder'
export { Emoji, gitHubEmojis } from '@tiptap-pro/extension-emoji'
export { TextAlign } from '@tiptap/extension-text-align'
export { TextStyle } from '@tiptap/extension-text-style'
export { FontFamily } from '@tiptap/extension-font-family'
export { Typography } from '@tiptap/extension-typography'
export { Color } from '@tiptap/extension-color'
export { FocusClasses as Focus } from '@tiptap/extension-focus'
export { Dropcursor } from '@tiptap/extension-dropcursor'
export { CollaborationCursor } from '@tiptap/extension-collaboration-cursor'
export { Subscript } from '@tiptap/extension-subscript'
export { Superscript } from '@tiptap/extension-superscript'
export { Paragraph } from '@tiptap/extension-paragraph'
export { BulletList } from '@tiptap/extension-bullet-list'
export { OrderedList } from '@tiptap/extension-ordered-list'
export { Collaboration } from '@tiptap/extension-collaboration'
export { TaskItem } from '@tiptap/extension-task-item'
export { TaskList } from '@tiptap/extension-task-list'
export { FileHandler } from '@tiptap-pro/extension-file-handler'
export { Details } from '@tiptap-pro/extension-details'
export { DetailsContent } from '@tiptap-pro/extension-details-content'
export { DetailsSummary } from '@tiptap-pro/extension-details-summary'
export { ImageFigure } from './Image'
export { Selection } from './Selection'
export { Table, TableCell, TableHeader, TableRow } from './Table'
export { CodeBlock } from './CodeBlock'
export { HorizontalRule } from './HorizontalRule'
export { Heading } from './Heading'
export { Document } from './Document'
export { TrailingNode } from './TrailingNode'
export { FontSize } from './FontSize'
export { Figure } from './Figure'
export { Figcaption } from './Figcaption'
export { Quote } from './BlockquoteFigure/Quote'
export { QuoteCaption } from './BlockquoteFigure/QuoteCaption'
export { Link } from './Link'
export { Columns, Column } from './MultiColumn'
export {emojiSuggestion} from './EmojiSuggestion' 
export {Image} from './Image'
export {Iframe} from './Iframe'
export {Blockquote} from './BlockquoteFigure'
// export { BlockquoteFigure } from './BlockquoteFigure'
// export { ImageUpload } from './ImageUpload'
// export {Image} from './Image/Image'
// import {Youtube} from '@tiptap/extension-youtube'
// export { AiWriter } from './AiWriter'
// export { AiImage } from './AiImage'
// export { SlashCommand } from './SlashCommand'

// export { ImageBlock } from './ImageBlock'
// import { Video } from './Video'
// import {Blockquote} from '@tiptap/extension-blockquote'
